// src/seed/venues.js
const venuesData = [
  {
    name: "The Royal Palace Jaipur",
    location: "Jaipur, Rajasthan, India",
    category: "Palace",
    image:
      "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&q=80",
    capacity: "500 - 2000",
    price: "₹85,000",
    description:
      "A majestic 18th-century palace featuring stunning Rajput architecture, sprawling courtyards, and luxurious suites. Perfect for royal weddings and grand celebrations with breathtaking views of the Pink City.",
    amenities: [
      "Valet Parking",
      "WiFi",
      "Air Conditioning",
      "Catering",
      "Decor Services",
      "Bridal Suite",
      "Audio/Video Equipment",
    ],
    featured: true,
    isActive: true,
    contactNumber: "+91 98765 43210",
    email: "royalpalace@violinevents.com",
    website: "www.royalpalacejaipur.com",
  },
  {
    name: "Taj Exotica Beach Resort",
    location: "Goa, India",
    category: "Beachfront Resort",
    image:
      "https://images.unsplash.com/photo-1512343879784-9602d5de7a10?w=800&q=80",
    capacity: "150 - 500",
    price: "₹65,000",
    description:
      "A luxurious beachfront resort offering stunning Arabian Sea views, private beach access, and world-class amenities. Ideal for romantic beach weddings and intimate celebrations.",
    amenities: [
      "Beach Access",
      "Pool",
      "Spa",
      "WiFi",
      "Air Conditioning",
      "Catering",
      "Valet Parking",
      "Water Sports",
    ],
    featured: true,
    isActive: true,
    contactNumber: "+91 98765 43211",
    email: "exotica@violinevents.com",
    website: "www.tajexotica.com",
  },
  {
    name: "Umaid Bhawan Heritage Palace",
    location: "Jodhpur, Rajasthan, India",
    category: "Heritage Palace",
    image:
      "https://images.unsplash.com/photo-1590582007337-f5d55ec5aaf0?w=800&q=80",
    capacity: "200 - 600",
    price: "₹95,000",
    description:
      "One of the world's largest private residences, this golden sandstone palace offers a blend of Art Deco and traditional Rajput architecture. Host royal weddings in the grand throne room.",
    amenities: [
      "Royal Suites",
      "WiFi",
      "Catering",
      "Decor Services",
      "Valet Parking",
      "Heritage Tours",
      "Fine Dining",
    ],
    featured: true,
    isActive: true,
    contactNumber: "+91 98765 43212",
    email: "umaidbhawan@violinevents.com",
    website: "www.umaidbhawan.com",
  },
  {
    name: "Alila Villas Uluwatu",
    location: "Bali, Indonesia",
    category: "Cliffside Resort",
    image:
      "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&q=80",
    capacity: "100 - 300",
    price: "₹75,000",
    description:
      "Perched on a cliff with panoramic Indian Ocean views, this ultra-luxury resort offers intimate weddings with sunset ceremonies overlooking the sea. Modern architecture meets traditional Balinese charm.",
    amenities: [
      "Private Villas",
      "Infinity Pool",
      "Spa",
      "WiFi",
      "Catering",
      "Bridal Suite",
      "Ocean Views",
    ],
    featured: true,
    isActive: true,
    contactNumber: "+62 812 3456 7890",
    email: "alila@violinevents.com",
    website: "www.alilahotels.com",
  },
  {
    name: "The Oberoi Amarvilas",
    location: "Agra, Uttar Pradesh, India",
    category: "Luxury Hotel",
    image:
      "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80",
    capacity: "100 - 400",
    price: "₹90,000",
    description:
      "Located just 600 meters from the Taj Mahal, this luxury hotel offers stunning views of the iconic monument. Every suite and venue boasts a view of the Taj Mahal, creating a truly magical wedding experience.",
    amenities: [
      "Taj Mahal View",
      "Spa",
      "WiFi",
      "Catering",
      "Decor Services",
      "Valet Parking",
      "Butler Service",
    ],
    featured: true,
    isActive: true,
    contactNumber: "+91 98765 43213",
    email: "amarvilas@violinevents.com",
    website: "www.oberoihotels.com",
  },
  {
    name: "The Leela Palace Udaipur",
    location: "Udaipur, Rajasthan, India",
    category: "Palace Hotel",
    image:
      "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&q=80",
    capacity: "150 - 500",
    price: "₹80,000",
    description:
      "Nestled on the banks of Lake Pichola, this palace hotel offers breathtaking lake views, royal suites, and impeccable hospitality. Perfect for destination weddings with a royal touch.",
    amenities: [
      "Lake Views",
      "Spa",
      "WiFi",
      "Catering",
      "Decor Services",
      "Valet Parking",
      "Bridal Suite",
    ],
    featured: false,
    isActive: true,
    contactNumber: "+91 98765 43214",
    email: "leelapalace@violinevents.com",
    website: "www.theleela.com",
  },
  {
    name: "ITC Grand Chola",
    location: "Chennai, Tamil Nadu, India",
    category: "Heritage Hotel",
    image:
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
    capacity: "200 - 800",
    price: "₹60,000",
    description:
      "A luxury hotel inspired by the grandeur of the Chola dynasty, featuring magnificent architecture, sprawling banquets, and world-class facilities. Ideal for large weddings and corporate events.",
    amenities: [
      "Grand Ballroom",
      "Spa",
      "WiFi",
      "Catering",
      "Decor Services",
      "Valet Parking",
      "Multiple Venues",
    ],
    featured: false,
    isActive: true,
    contactNumber: "+91 98765 43215",
    email: "grandchola@violinevents.com",
    website: "www.itchotels.com",
  },
  {
    name: "Vivanta by Taj - Bekal",
    location: "Kerala, India",
    category: "Resort",
    image:
      "https://images.unsplash.com/photo-1596178060671-7a80dc8059ea?w=800&q=80",
    capacity: "100 - 300",
    price: "₹55,000",
    description:
      "Set amidst lush greenery and backwaters, this resort offers a serene and romantic setting for intimate weddings. Traditional Kerala architecture meets modern luxury.",
    amenities: [
      "Backwater Views",
      "Pool",
      "Spa",
      "WiFi",
      "Catering",
      "Ayurvedic Treatments",
      "Water Sports",
    ],
    featured: false,
    isActive: true,
    contactNumber: "+91 98765 43216",
    email: "bekal@violinevents.com",
    website: "www.tajhotels.com",
  },
  {
    name: "The Rambagh Palace",
    location: "Jaipur, Rajasthan, India",
    category: "Heritage Palace",
    image:
      "https://images.unsplash.com/photo-1590582007337-f5d55ec5aaf0?w=800&q=80",
    capacity: "150 - 400",
    price: "₹88,000",
    description:
      "The former residence of the Maharaja of Jaipur, this stunning palace offers royal suites, sprawling gardens, and a sense of timeless elegance. Experience a truly royal wedding.",
    amenities: [
      "Royal Suites",
      "Gardens",
      "WiFi",
      "Catering",
      "Decor Services",
      "Valet Parking",
      "Heritage Tours",
    ],
    featured: false,
    isActive: true,
    contactNumber: "+91 98765 43217",
    email: "rambagh@violinevents.com",
    website: "www.rambaghpalace.com",
  },
  {
    name: "The St. Regis Maldives",
    location: "Vommuli Island, Maldives",
    category: "Luxury Island Resort",
    image:
      "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80",
    capacity: "50 - 200",
    price: "₹120,000",
    description:
      "An ultra-luxury island resort offering overwater villas, pristine beaches, and crystal-clear waters. Perfect for intimate, exclusive weddings in paradise with world-class service.",
    amenities: [
      "Overwater Villas",
      "Private Beach",
      "Pool",
      "Spa",
      "WiFi",
      "Catering",
      "Water Sports",
      "Butler Service",
    ],
    featured: true,
    isActive: true,
    contactNumber: "+960 777 1234",
    email: "stregis@violinevents.com",
    website: "www.stregismaldives.com",
  },
];

module.exports = venuesData;
